main: com.github.sgehren.buildpro.Core
name: BuildPro
version: 1.0.0
api-version: 1.14
author: SGEhren
description: A plugin for Professional Builders
commands:
  selector:
    description: Gives the player the selector object
    usage: /<command>
  copy:
    description: Copies the selection
    usage: /<command>
  paste:
    description: Pastes the selection
    usage: /<command>
  set:
    description: Sets the blocks in the selection
    usage: /<command>
  replace:
    description: Replace certain blocks in the selection with a specific material
    usage: /<command>